### ISSUE TITLE
Create unit test verifying behavior when retrieving an edge to a non-existent or invisible vertex.

### ISSUE THREAD

**Issue by kunklejr** [lumifyio/securegraph#16]
Create a vertex with auth A. Create vertex with auth B. Create an edge with auth A between the two vertices. Verify:

1.  The call to getEdges from A should return the edge. The call to getVertex should return null.
2. Delete edge with auth A. Edges on vertex B should not include A.

**Comment by joeferner** [comment]
This cannot be done. Without elevating to get vertex with auth B. The check for edge existence also cannot be done efficiently without looking up all edges.
