### ISSUE TITLE
Example Issue:  Unable to create table securegraph_v

### ISSUE THREAD

**Issue by Lab41PaulM** [lumifyio/securegraph#31]
I can log into the accumulo shell and create tables, however when running the example code, I get the following runtime exception.  Any guidance would be appreciated.  I am using the same credentials that I use via accumulo shell. 

java.lang.RuntimeException: Unable to create table securegraph_v    
 at org.securegraph.accumulo.AccumuloGraph.ensureTableExists(AccumuloGraph.java:107)

when running...
// specify Accumulo config, more options than shown are available
Map mapConfig = new HashMap();
mapConfig.put(AccumuloGraphConfiguration.USE_SERVER_SIDE_ELEMENT_VISIBILITY_ROW_FILTER, false);
mapConfig.put(AccumuloGraphConfiguration.ACCUMULO_INSTANCE_NAME, "instance_name");
mapConfig.put(AccumuloGraphConfiguration.ACCUMULO_USERNAME, "username");
mapConfig.put(AccumuloGraphConfiguration.ACCUMULO_PASSWORD, "password");
mapConfig.put(AccumuloGraphConfiguration.ZOOKEEPER_SERVERS, "localhost");

AccumuloGraphConfiguration graphConfig = new AccumuloGraphConfiguration(mapConfig);
Graph graph = AccumuloGraph.create(graphConfig);

**Comment by Lab41PaulM** [comment]
Found out that this issue did not occur with the latest 0.9.0 version rather than 0.7.0 version which the example in the README recommends.

**Comment by estkae** [comment]
sorry but i have the same issue with version 0.10.0 has anybody an idea what is Happens, can ich Connect to a accumulo - cluster. 
I think that is a try and error system.
